export const ADD_TO_CART = "@cart/ADD_TO_CART";
export const REMOVE_FROM_CART = "@cart/REMOVE_FROM_CART";
export const FETCH_PRODUCTS_PENDING = "@products/FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_ERROR = "@products/FETCH_PRODUCTS_ERROR";
export const FETCH_PRODUCTS_FULFILLED = "@products/FETCH_PRODUCTS_FULFILLED";
